### ISSUE TITLE
[Feature] Memory Leak

### ISSUE THREAD

**Issue by hseesh** [Morterolath/FlowFieldNavigation#1]
The current version seems to have some memory leaks，when i run the test sence without do anything, I got some warnings

> Internal: JobTempAlloc has allocations that are more than the maximum lifespan of 4 frames old - this is not allowed and likely a leak
> To Debug, run app with -diag-job-temp-memory-leak-validation cmd line argument. This will output the callstacks of the leaked allocations.

My Unity version：2022.3.14f1c1

**Comment by Morterolath** [comment]
According to the call stack, leak source is SimulationInputHandler.cs, line 99 and 100. Looks like an internal unity bug caused by .AsArray() method of NativeList which copies the pointer and uses it as an array without allocating whole new memory. This might result in leak detection to track two pointers pointing to the same address independently.
Unity's leak detection system is a little bit lame unfortunately :/ Don't worry about leak warnings and stuff.

**Comment by hseesh** [comment]
That's fine! I hope all goes well for us and I will continue to explore this awesome project!
